name: Backup

on: [push, delete]

jobs:
  to_bitbucket:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@bitbucket.org:tuplo/dynoexpr.git
          ssh_private_key: ${{ secrets.BITBUCKET_SSH_PRIVATE_KEY }}
